export enum PaymentMethod { COD = 'COD', ONLINE_PAYMENT = 'ONLINE_PAYMENT' }
export enum PaymentStatus {
  PENDING = 'PENDING', PROCESSING = 'PROCESSING', SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED', REFUND_PENDING = 'REFUND_PENDING',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED', REFUNDED = 'REFUNDED',
}
export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT', PROCESSING = 'PROCESSING',
  PARTIALLY_CANCELLED = 'PARTIALLY_CANCELLED', SHIPPING = 'SHIPPING',
  COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED',
}
export enum SellerOrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT', PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED', PREPARING = 'PREPARING', SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED',
}
export enum ReservationStatus { ACTIVE = 'ACTIVE', COMMITTED = 'COMMITTED', RELEASED = 'RELEASED', EXPIRED = 'EXPIRED' }
export enum HistoryActorType { USER = 'USER', SELLER = 'SELLER', ADMIN = 'ADMIN', SYSTEM = 'SYSTEM' }
export enum OutboxStatus { PENDING = 'PENDING', PUBLISHED = 'PUBLISHED', FAILED = 'FAILED' }

