/**
 * HUKI EBOOK - Error Codes
 *
 * Standardized error codes for all services.
 * Format: {DOMAIN}_{SPECIFIC_ERROR}
 */

// ============================================
// AUTHENTICATION & AUTHORIZATION
// ============================================

export enum ErrorCode {
  // AUTH - Authentication (401)
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_INTERNAL_API_KEY_INVALID = 'AUTH_INTERNAL_API_KEY_INVALID',
  AUTH_TOKEN_REFRESH_FAILED = 'AUTH_TOKEN_REFRESH_FAILED',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGIN_INVALID_CREDENTIALS = 'AUTH_LOGIN_INVALID_CREDENTIALS',
  AUTH_LOGIN_ACCOUNT_BLOCKED = 'AUTH_LOGIN_ACCOUNT_BLOCKED',
  AUTH_LOGIN_ACCOUNT_PENDING = 'AUTH_LOGIN_ACCOUNT_PENDING',
  AUTH_REGISTER_FAILED = 'AUTH_REGISTER_FAILED',
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_PASSWORD_WEAK = 'AUTH_PASSWORD_WEAK',
  AUTH_PASSWORD_INCORRECT = 'AUTH_PASSWORD_INCORRECT',
  AUTH_PASSWORD_SAME = 'AUTH_PASSWORD_SAME',
  AUTH_RESET_TOKEN_INVALID = 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED = 'AUTH_RESET_TOKEN_EXPIRED',

  // AUTHZ - Authorization (403)
  AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN',
  AUTHZ_ROLE_INSUFFICIENT = 'AUTHZ_ROLE_INSUFFICIENT',
  AUTHZ_NOT_OWNER = 'AUTHZ_NOT_OWNER',
  AUTHZ_NOT_MEMBER = 'AUTHZ_NOT_MEMBER',
  AUTHZ_BUSINESS_SUSPENDED = 'AUTHZ_BUSINESS_SUSPENDED',

  // ============================================
  // USER
  // ============================================
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_PHONE_EXISTS = 'USER_PHONE_EXISTS',
  USER_PROFILE_INCOMPLETE = 'USER_PROFILE_INCOMPLETE',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_EMAIL_NOT_VERIFIED = 'USER_EMAIL_NOT_VERIFIED',

  // ============================================
  // BUSINESS
  // ============================================
  BUSINESS_NOT_FOUND = 'BUSINESS_NOT_FOUND',
  BUSINESS_ALREADY_EXISTS = 'BUSINESS_ALREADY_EXISTS',
  BUSINESS_REGISTRY_NOT_FOUND = 'BUSINESS_REGISTRY_NOT_FOUND',
  BUSINESS_REGISTRY_MISMATCH = 'BUSINESS_REGISTRY_MISMATCH',
  BUSINESS_TAX_CODE_EXISTS = 'BUSINESS_TAX_CODE_EXISTS',
  BUSINESS_ENTERPRISE_CODE_EXISTS = 'BUSINESS_ENTERPRISE_CODE_EXISTS',
  BUSINESS_NOT_APPROVED = 'BUSINESS_NOT_APPROVED',
  BUSINESS_SUSPENDED = 'BUSINESS_SUSPENDED',
  BUSINESS_CANNOT_DELETE = 'BUSINESS_CANNOT_DELETE',
  BUSINESS_LEGAL_INFO_LOCKED = 'BUSINESS_LEGAL_INFO_LOCKED',

  // ============================================
  // STORE
  // ============================================
  STORE_NOT_FOUND = 'STORE_NOT_FOUND',
  STORE_ALREADY_EXISTS = 'STORE_ALREADY_EXISTS',
  STORE_SLUG_EXISTS = 'STORE_SLUG_EXISTS',
  STORE_NOT_ACTIVE = 'STORE_NOT_ACTIVE',
  STORE_SUSPENDED = 'STORE_SUSPENDED',
  STORE_CANNOT_DELETE = 'STORE_CANNOT_DELETE',

  // ============================================
  // MEMBER
  // ============================================
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  MEMBER_INVITATION_EXPIRED = 'MEMBER_INVITATION_EXPIRED',
  MEMBER_INVITATION_INVALID = 'MEMBER_INVITATION_INVALID',
  MEMBER_CANNOT_LEAVE = 'MEMBER_CANNOT_LEAVE',
  MEMBER_ROLE_IMMUTABLE = 'MEMBER_ROLE_IMMUTABLE',

  // ============================================
  // BOOK
  // ============================================
  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  BOOK_NOT_PUBLISHED = 'BOOK_NOT_PUBLISHED',
  BOOK_ARCHIVED = 'BOOK_ARCHIVED',
  BOOK_HIDDEN = 'BOOK_HIDDEN',
  BOOK_SUSPENDED = 'BOOK_SUSPENDED',
  BOOK_SLUG_EXISTS = 'BOOK_SLUG_EXISTS',
  BOOK_ISBN_EXISTS = 'BOOK_ISBN_EXISTS',
  BOOK_NOT_FROM_STORE = 'BOOK_NOT_FROM_STORE',
  BOOK_FORMAT_NOT_AVAILABLE = 'BOOK_FORMAT_NOT_AVAILABLE',
  BOOK_COVER_REQUIRED = 'BOOK_COVER_REQUIRED',
  BOOK_FILE_REQUIRED = 'BOOK_FILE_REQUIRED',
  BOOK_UNAUTHORIZED = 'BOOK_UNAUTHORIZED',
  BOOK_PRICE_INVALID = 'BOOK_PRICE_INVALID',

  // ============================================
  // INVENTORY
  // ============================================
  INVENTORY_NOT_FOUND = 'INVENTORY_NOT_FOUND',
  INVENTORY_INSUFFICIENT = 'INVENTORY_INSUFFICIENT',
  INVENTORY_NEGATIVE = 'INVENTORY_NEGATIVE',
  INVENTORY_RESERVATION_FAILED = 'INVENTORY_RESERVATION_FAILED',
  INVENTORY_RESERVATION_EXPIRED = 'INVENTORY_RESERVATION_EXPIRED',

  // ============================================
  // CART
  // ============================================
  CART_NOT_FOUND = 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  CART_ITEM_EXISTS = 'CART_ITEM_EXISTS',
  CART_DIGITAL_ALREADY_OWNED = 'CART_DIGITAL_ALREADY_OWNED',
  CART_MAX_ITEMS = 'CART_MAX_ITEMS',
  CART_QUANTITY_INVALID = 'CART_QUANTITY_INVALID',

  // ============================================
  // CHECKOUT
  // ============================================
  CART_EMPTY = 'CART_EMPTY',
  CHECKOUT_SESSION_NOT_FOUND = 'CHECKOUT_SESSION_NOT_FOUND',
  CHECKOUT_SESSION_CONSUMED = 'CHECKOUT_SESSION_CONSUMED',
  CHECKOUT_SESSION_EXPIRED = 'CHECKOUT_SESSION_EXPIRED',
  CHECKOUT_SHIPPING_REQUIRED = 'CHECKOUT_SHIPPING_REQUIRED',
  CHECKOUT_SHIPPING_INVALID = 'CHECKOUT_SHIPPING_INVALID',
  CHECKOUT_QUOTE_EXPIRED = 'CHECKOUT_QUOTE_EXPIRED',
  CHECKOUT_QUOTE_UNAVAILABLE = 'CHECKOUT_QUOTE_UNAVAILABLE',
  CHECKOUT_PAYMENT_REQUIRED = 'CHECKOUT_PAYMENT_REQUIRED',
  CHECKOUT_DIGITAL_COD_NOT_ALLOWED = 'CHECKOUT_DIGITAL_COD_NOT_ALLOWED',
  CHECKOUT_IDEMPOTENCY_CONFLICT = 'CHECKOUT_IDEMPOTENCY_CONFLICT',
  SHIPPING_ADDRESS_REQUIRED = 'SHIPPING_ADDRESS_REQUIRED',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  PAYMENT_PROVIDER_INVALID = 'PAYMENT_PROVIDER_INVALID',
  COD_NOT_AVAILABLE = 'COD_NOT_AVAILABLE',

  // ============================================
  // ORDER
  // ============================================
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID = 'ORDER_ALREADY_PAID',
  ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED',
  ORDER_ALREADY_COMPLETED = 'ORDER_ALREADY_COMPLETED',
  ORDER_CANNOT_CANCEL = 'ORDER_CANNOT_CANCEL',
  ORDER_NOT_FROM_USER = 'ORDER_NOT_FROM_USER',
  ORDER_NOT_FROM_STORE = 'ORDER_NOT_FROM_STORE',
  ORDER_STATUS_TRANSITION_INVALID = 'ORDER_STATUS_TRANSITION_INVALID',
  SELLER_ORDER_NOT_FOUND = 'SELLER_ORDER_NOT_FOUND',
  SELLER_ORDER_CANNOT_CANCEL = 'SELLER_ORDER_CANNOT_CANCEL',

  // ============================================
  // PAYMENT
  // ============================================
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_SIGNATURE_INVALID = 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_WEBHOOK_FAILED = 'PAYMENT_WEBHOOK_FAILED',
  PAYMENT_PROVIDER_ERROR = 'PAYMENT_PROVIDER_ERROR',

  // ============================================
  // REFUND
  // ============================================
  REFUND_NOT_FOUND = 'REFUND_NOT_FOUND',
  REFUND_NOT_ALLOWED = 'REFUND_NOT_ALLOWED',
  REFUND_AMOUNT_INVALID = 'REFUND_AMOUNT_INVALID',
  REFUND_EXCEEDS_PAID = 'REFUND_EXCEEDS_PAID',
  REFUND_ALREADY_PROCESSED = 'REFUND_ALREADY_PROCESSED',

  // ============================================
  // SHIPMENT
  // ============================================
  SHIPMENT_NOT_FOUND = 'SHIPMENT_NOT_FOUND',
  SHIPMENT_STATUS_TRANSITION_INVALID = 'SHIPMENT_STATUS_TRANSITION_INVALID',
  SHIPMENT_CANNOT_CANCEL = 'SHIPMENT_CANNOT_CANCEL',
  SHIPMENT_STAFF_NOT_FOUND = 'SHIPMENT_STAFF_NOT_FOUND',
  SHIPMENT_STAFF_INACTIVE = 'SHIPMENT_STAFF_INACTIVE',
  SHIPMENT_STAFF_ASSIGNED = 'SHIPMENT_STAFF_ASSIGNED',
  SHIPMENT_STAFF_NOT_ASSIGNED = 'SHIPMENT_STAFF_NOT_ASSIGNED',
  SHIPMENT_CARRIER_ERROR = 'SHIPMENT_CARRIER_ERROR',

  // ============================================
  // ADDRESS
  // ============================================
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  ADDRESS_DEFAULT_INVALID = 'ADDRESS_DEFAULT_INVALID',

  // ============================================
  // LIBRARY (Book Access)
  // ============================================
  LIBRARY_ACCESS_DENIED = 'LIBRARY_ACCESS_DENIED',
  LIBRARY_BOOK_NOT_FOUND = 'LIBRARY_BOOK_NOT_FOUND',
  LIBRARY_ALREADY_GRANTED = 'LIBRARY_ALREADY_GRANTED',
  LIBRARY_ACCESS_REVOKED = 'LIBRARY_ACCESS_REVOKED',
  LIBRARY_FILE_NOT_FOUND = 'LIBRARY_FILE_NOT_FOUND',

  // ============================================
  // VOUCHER
  // ============================================
  VOUCHER_NOT_FOUND = 'VOUCHER_NOT_FOUND',
  VOUCHER_EXPIRED = 'VOUCHER_EXPIRED',
  VOUCHER_NOT_STARTED = 'VOUCHER_NOT_STARTED',
  VOUCHER_EXHAUSTED = 'VOUCHER_EXHAUSTED',
  VOUCHER_LIMIT_REACHED = 'VOUCHER_LIMIT_REACHED',
  VOUCHER_NOT_APPLICABLE = 'VOUCHER_NOT_APPLICABLE',
  VOUCHER_MIN_ORDER_NOT_MET = 'VOUCHER_MIN_ORDER_NOT_MET',
  VOUCHER_STACKING_NOT_ALLOWED = 'VOUCHER_STACKING_NOT_ALLOWED',
  VOUCHER_CODE_EXISTS = 'VOUCHER_CODE_EXISTS',

  // ============================================
  // FLASH SALE
  // ============================================
  FLASH_SALE_NOT_FOUND = 'FLASH_SALE_NOT_FOUND',
  FLASH_SALE_NOT_ACTIVE = 'FLASH_SALE_NOT_ACTIVE',
  FLASH_SALE_ITEM_NOT_FOUND = 'FLASH_SALE_ITEM_NOT_FOUND',
  FLASH_SALE_STOCK_EXHAUSTED = 'FLASH_SALE_STOCK_EXHAUSTED',
  FLASH_SALE_USER_LIMIT_REACHED = 'FLASH_SALE_USER_LIMIT_REACHED',

  // ============================================
  // REVIEW
  // ============================================
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_PURCHASE_REQUIRED = 'REVIEW_PURCHASE_REQUIRED',
  REVIEW_CANNOT_EDIT = 'REVIEW_CANNOT_EDIT',
  REVIEW_MODERATED = 'REVIEW_MODERATED',

  // ============================================
  // FORUM
  // ============================================
  FORUM_POST_NOT_FOUND = 'FORUM_POST_NOT_FOUND',
  FORUM_POST_LOCKED = 'FORUM_POST_LOCKED',
  FORUM_POST_DELETED = 'FORUM_POST_DELETED',
  FORUM_COMMENT_NOT_FOUND = 'FORUM_COMMENT_NOT_FOUND',
  FORUM_REPORT_EXISTS = 'FORUM_REPORT_EXISTS',

  // ============================================
  // CHAT
  // ============================================
  CHAT_CONVERSATION_NOT_FOUND = 'CHAT_CONVERSATION_NOT_FOUND',
  CHAT_MESSAGE_NOT_FOUND = 'CHAT_MESSAGE_NOT_FOUND',
  CHAT_BLOCKED = 'CHAT_BLOCKED',
  CHAT_BUSINESS_SUSPENDED = 'CHAT_BUSINESS_SUSPENDED',
  CHAT_MESSAGE_TOO_LONG = 'CHAT_MESSAGE_TOO_LONG',

  // ============================================
  // NOTIFICATION
  // ============================================
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_PREFERENCE_NOT_FOUND = 'NOTIFICATION_PREFERENCE_NOT_FOUND',
  NOTIFICATION_DEVICE_NOT_FOUND = 'NOTIFICATION_DEVICE_NOT_FOUND',

  // ============================================
  // MODERATION
  // ============================================
  MODERATION_REPORT_NOT_FOUND = 'MODERATION_REPORT_NOT_FOUND',
  MODERATION_REPORT_ALREADY_EXISTS = 'MODERATION_REPORT_ALREADY_EXISTS',
  MODERATION_CONTENT_DELETED = 'MODERATION_CONTENT_DELETED',

  // ============================================
  // VALIDATION
  // ============================================
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  VALIDATION_EMAIL = 'VALIDATION_EMAIL',
  VALIDATION_PHONE = 'VALIDATION_PHONE',
  VALIDATION_URL = 'VALIDATION_URL',
  VALIDATION_MIN_LENGTH = 'VALIDATION_MIN_LENGTH',
  VALIDATION_MAX_LENGTH = 'VALIDATION_MAX_LENGTH',
  VALIDATION_MIN_VALUE = 'VALIDATION_MIN_VALUE',
  VALIDATION_MAX_VALUE = 'VALIDATION_MAX_VALUE',
  VALIDATION_PATTERN = 'VALIDATION_PATTERN',

  // ============================================
  // RATE LIMIT
  // ============================================
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_LOGIN = 'RATE_LIMIT_LOGIN',
  RATE_LIMIT_REGISTER = 'RATE_LIMIT_REGISTER',

  // ============================================
  // SYSTEM
  // ============================================
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  SYSTEM_UNAVAILABLE = 'SYSTEM_UNAVAILABLE',
  SYSTEM_DATABASE_ERROR = 'SYSTEM_DATABASE_ERROR',
  SYSTEM_EXTERNAL_SERVICE_ERROR = 'SYSTEM_EXTERNAL_SERVICE_ERROR',
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',

  // ============================================
  // SESSION
  // ============================================
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_DEVICE_MISMATCH = 'SESSION_DEVICE_MISMATCH',

  // ============================================
  // CATEGORY / AUTHOR / PUBLISHER
  // ============================================
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_CHILDREN = 'CATEGORY_HAS_CHILDREN',
  AUTHOR_NOT_FOUND = 'AUTHOR_NOT_FOUND',
  AUTHOR_SLUG_EXISTS = 'AUTHOR_SLUG_EXISTS',
  PUBLISHER_NOT_FOUND = 'PUBLISHER_NOT_FOUND',
  PUBLISHER_SLUG_EXISTS = 'PUBLISHER_SLUG_EXISTS',

  // ============================================
  // BANNER
  // ============================================
  BANNER_NOT_FOUND = 'BANNER_NOT_FOUND',
  BANNER_INVALID_DATE_RANGE = 'BANNER_INVALID_DATE_RANGE',
}
